# Generated by Django 2.2.2 on 2019-07-14 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import ugbags.get_username


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('subject', models.CharField(blank=True, max_length=200, null=True)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RateBag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RateSeller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RateShop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ReportBag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ReportShop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ReportUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=900)),
                ('contact', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shops', to=settings.AUTH_USER_MODEL)),
                ('update_by', models.ForeignKey(default=ugbags.get_username.get_current_user, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('gender', models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=1)),
                ('photo', models.ImageField(upload_to='resources/profile_pics/')),
                ('User_type', models.CharField(choices=[('b', 'buyer'), ('s', 'seller'), ('a', 'admin')], max_length=1)),
                ('nin', models.CharField(max_length=14)),
                ('owner', models.ForeignKey(default=ugbags.get_username.get_current_user, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('update_by', models.ForeignKey(default=ugbags.get_username.get_current_user, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('bag_type', models.CharField(choices=[('a', 'office'), ('b', 'laptop'), ('c', 'lady_hand_bag'), ('d', 'school'), ('e', 'travel'), ('f', "men's wallet"), ('g', "women's wallet")], max_length=1)),
                ('bag_size', models.CharField(choices=[('a', 'small'), ('b', 'big'), ('c', 'medium'), ('d', 'large'), ('e', 'extra-large'), ('f', 'extra-small')], max_length=1)),
                ('skin_type', models.CharField(choices=[('a', 'lether'), ('b', 'cloth')], max_length=1)),
                ('bag_color', models.CharField(choices=[('a', 'white'), ('b', 'black'), ('c', 'red'), ('c', 'blue'), ('d', 'purple'), ('e', 'green'), ('f', 'yellow'), ('g', 'grey'), ('h', 'pink'), ('i', 'other'), ('j', 'not specific')], max_length=1)),
                ('buying_type', models.CharField(choices=[('a', 'not negotiable'), ('b', 'slightly negotiable'), ('c', 'negotiable')], max_length=1)),
                ('payment_type', models.CharField(choices=[('a', 'pay via app'), ('b', 'pay cash on delievery')], max_length=1)),
                ('image_one', models.ImageField(upload_to='resources/bag_image/one')),
                ('image_two', models.ImageField(blank=True, null=True, upload_to='resources/bag_image/two')),
                ('image_three', models.ImageField(blank=True, null=True, upload_to='resources/bag_image/three')),
                ('image_four', models.ImageField(blank=True, null=True, upload_to='resources/bag_image/four')),
                ('simple_description', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bag', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bag', to='ugbags.Shop')),
                ('update_by', models.ForeignKey(default=ugbags.get_username.get_current_user, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('id',)},
            },
        ),
    ]
