# Generated by Django 2.2.2 on 2019-07-15 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugbags', '0002_auto_20190714_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False, unique=True),
        ),
    ]
